version: "3"
x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.sample
    <<: *default-logging

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    <<: *default-logging

  redis:
    image: redis:alpine
    command: [
        "sh", "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: .env.sample
    <<: *default-logging
    restart: always